/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.may;

/**
 *
 * @author swati
 */
public class DetReport extends javax.swing.JPanel {

    /**
     * Creates new form DetReport
     */
    public DetReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageEnt2 = new javax.swing.JLabel();
        manageEnt1 = new javax.swing.JLabel();
        totalSeniorPpl = new javax.swing.JLabel();
        hasHeartPblm = new javax.swing.JLabel();
        noheartPrblm = new javax.swing.JLabel();
        hasSensor = new javax.swing.JLabel();
        totTransReq1 = new javax.swing.JLabel();
        hasNoSensor = new javax.swing.JLabel();
        sendToDoc = new javax.swing.JLabel();
        totSeniorPPLField = new javax.swing.JTextField();
        seniorsWithHeartPrbField = new javax.swing.JTextField();
        senWithNoHeartProbField = new javax.swing.JTextField();
        senWithSensorField = new javax.swing.JTextField();
        senShareInfoField = new javax.swing.JTextField();
        senNoSensorDevField = new javax.swing.JTextField();
        senSendDataToDocField = new javax.swing.JTextField();
        barchartBtn = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        manageEnt2.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        manageEnt2.setText("Heart Help Mayor Work Area");

        manageEnt1.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        manageEnt1.setText("View Detailed Report");

        totalSeniorPpl.setFont(new java.awt.Font("Malayalam MN", 3, 18)); // NOI18N
        totalSeniorPpl.setText("Total No of Senior People who are in need of Help");

        hasHeartPblm.setFont(new java.awt.Font("Malayalam MN", 3, 18)); // NOI18N
        hasHeartPblm.setText("No of Senior people with heart problem");

        noheartPrblm.setFont(new java.awt.Font("Malayalam MN", 3, 18)); // NOI18N
        noheartPrblm.setText("No of Senior people with no heart problem ");

        hasSensor.setFont(new java.awt.Font("Malayalam MN", 3, 18)); // NOI18N
        hasSensor.setText("Total No of seniors who has sensor device");

        totTransReq1.setFont(new java.awt.Font("Malayalam MN", 3, 18)); // NOI18N
        totTransReq1.setText("Total No of Seniors who share Vital Info");

        hasNoSensor.setFont(new java.awt.Font("Malayalam MN", 3, 18)); // NOI18N
        hasNoSensor.setText("Total No of Seniors who dont have sensor device");

        sendToDoc.setFont(new java.awt.Font("Malayalam MN", 3, 18)); // NOI18N
        sendToDoc.setText("Total No of Seniors who send data to doctor");

        totSeniorPPLField.setEditable(false);
        totSeniorPPLField.setBackground(new java.awt.Color(153, 204, 0));

        seniorsWithHeartPrbField.setEditable(false);
        seniorsWithHeartPrbField.setBackground(new java.awt.Color(153, 204, 0));

        senWithNoHeartProbField.setEditable(false);
        senWithNoHeartProbField.setBackground(new java.awt.Color(153, 204, 0));

        senWithSensorField.setEditable(false);
        senWithSensorField.setBackground(new java.awt.Color(153, 204, 0));

        senShareInfoField.setEditable(false);
        senShareInfoField.setBackground(new java.awt.Color(153, 204, 0));

        senNoSensorDevField.setEditable(false);
        senNoSensorDevField.setBackground(new java.awt.Color(153, 204, 0));

        senSendDataToDocField.setEditable(false);
        senSendDataToDocField.setBackground(new java.awt.Color(153, 204, 0));

        barchartBtn.setText("View Bar Chart");
        barchartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barchartBtnActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(manageEnt1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 278, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(totalSeniorPpl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 458, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(hasHeartPblm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 378, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(noheartPrblm))
                                .add(96, 96, 96)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(senWithNoHeartProbField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(seniorsWithHeartPrbField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(totSeniorPPLField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                    .add(sendToDoc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 431, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(senSendDataToDocField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                    .add(hasNoSensor)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(senNoSensorDevField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                    .add(totTransReq1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 399, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(159, 159, 159)
                                    .add(senShareInfoField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(131, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(hasSensor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(senWithSensorField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(131, 131, 131))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(manageEnt2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 366, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(193, 193, 193))))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(46, 46, 46)
                .add(backJButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(barchartBtn)
                .add(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(manageEnt2)
                .add(18, 18, 18)
                .add(manageEnt1)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(totalSeniorPpl)
                    .add(totSeniorPPLField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(hasHeartPblm)
                    .add(seniorsWithHeartPrbField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(noheartPrblm)
                    .add(senWithNoHeartProbField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(38, 38, 38)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(hasSensor)
                    .add(senWithSensorField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(totTransReq1)
                    .add(senShareInfoField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(46, 46, 46)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(hasNoSensor)
                    .add(senNoSensorDevField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(sendToDoc)
                    .add(senSendDataToDocField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(barchartBtn)
                    .add(backJButton))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void barchartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barchartBtnActionPerformed
        populateBarDataChartPanel();
    }//GEN-LAST:event_barchartBtnActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton barchartBtn;
    private javax.swing.JLabel hasHeartPblm;
    private javax.swing.JLabel hasNoSensor;
    private javax.swing.JLabel hasSensor;
    private javax.swing.JLabel manageEnt1;
    private javax.swing.JLabel manageEnt2;
    private javax.swing.JLabel noheartPrblm;
    private javax.swing.JTextField senNoSensorDevField;
    private javax.swing.JTextField senSendDataToDocField;
    private javax.swing.JTextField senShareInfoField;
    private javax.swing.JTextField senWithNoHeartProbField;
    private javax.swing.JTextField senWithSensorField;
    private javax.swing.JLabel sendToDoc;
    private javax.swing.JTextField seniorsWithHeartPrbField;
    private javax.swing.JTextField totSeniorPPLField;
    private javax.swing.JLabel totTransReq1;
    private javax.swing.JLabel totalSeniorPpl;
    // End of variables declaration//GEN-END:variables
}
