/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.seeker;

/**
 *
 * @author keert
 */
public class submitrqst extends javax.swing.JPanel {

    /**
     * Creates new form submitrqst
     */
    public submitrqst() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderField = new javax.swing.JTextField();
        viewYourProfile1 = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        serviceTypeTxtField = new javax.swing.JTextField();
        submitRequest = new javax.swing.JLabel();
        commentsTextField = new javax.swing.JTextField();
        LastName1 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        gender = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        dobField = new javax.swing.JFormattedTextField();
        cancelHelpRequest = new javax.swing.JButton();
        submitHelpRequest = new javax.swing.JButton();
        firstName = new javax.swing.JLabel();
        viewYourProfile = new javax.swing.JLabel();
        helpNameTxtField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        gender1 = new javax.swing.JLabel();
        dateOfBirth = new javax.swing.JLabel();
        firstName1 = new javax.swing.JLabel();

        genderField.setEnabled(false);

        viewYourProfile1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        viewYourProfile1.setText("Help Request Details:");

        LastName.setText("Last Name:");

        serviceTypeTxtField.setEditable(false);
        serviceTypeTxtField.setEnabled(false);

        submitRequest.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        submitRequest.setText("Submit Request toVolunteer For Help:");

        LastName1.setText("Help Type:");

        firstNameField.setEditable(false);
        firstNameField.setEnabled(false);

        gender.setText("Gender:");

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        dobField.setEnabled(false);

        cancelHelpRequest.setText("Cancel");

        submitHelpRequest.setText("Submit");
        submitHelpRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitHelpRequestActionPerformed(evt);
            }
        });

        firstName.setText("First Name:");

        viewYourProfile.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        viewYourProfile.setText("Volunteer Details:");

        helpNameTxtField.setEditable(false);
        helpNameTxtField.setEnabled(false);

        lastNameField.setEditable(false);
        lastNameField.setEnabled(false);

        gender1.setText("Comments:");

        dateOfBirth.setText("Date Of Birth ");

        firstName1.setText("Need Help:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(46, 46, 46)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(backJButton)
                            .add(layout.createSequentialGroup()
                                .add(126, 126, 126)
                                .add(submitRequest, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 472, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(layout.createSequentialGroup()
                        .add(108, 108, 108)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(viewYourProfile)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(dateOfBirth)
                                            .add(LastName))
                                        .add(layout.createSequentialGroup()
                                            .add(gender)
                                            .add(12, 12, 12)))
                                    .add(firstName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(13, 13, 13)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(genderField)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, lastNameField)
                                    .add(dobField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                    .add(firstNameField))))
                        .add(80, 80, 80)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(viewYourProfile1)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                            .add(LastName1)
                                            .add(51, 51, 51))
                                        .add(layout.createSequentialGroup()
                                            .add(gender1)
                                            .add(12, 12, 12)))
                                    .add(layout.createSequentialGroup()
                                        .add(firstName1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(42, 42, 42)))
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(helpNameTxtField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 184, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(commentsTextField)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, serviceTypeTxtField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 181, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))))
                    .add(layout.createSequentialGroup()
                        .add(328, 328, 328)
                        .add(submitHelpRequest)
                        .add(18, 18, 18)
                        .add(cancelHelpRequest)))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(19, 19, 19)
                .add(submitRequest)
                .add(59, 59, 59)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(viewYourProfile)
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(firstName)
                            .add(firstNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(LastName)
                            .add(lastNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(dateOfBirth)
                            .add(dobField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(genderField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(gender)))
                    .add(layout.createSequentialGroup()
                        .add(viewYourProfile1)
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(firstName1)
                            .add(helpNameTxtField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(LastName1)
                            .add(serviceTypeTxtField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(50, 50, 50)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(commentsTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(gender1))))
                .add(57, 57, 57)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(submitHelpRequest)
                    .add(cancelHelpRequest))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(backJButton)
                .add(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        RequestVolunteerForHelp requestVolunteerForHelp = (RequestVolunteerForHelp) component;
        requestVolunteerForHelp.populateHelpHistoryTable();
        requestVolunteerForHelp.populateNeedHelpListTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitHelpRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitHelpRequestActionPerformed
        if(commentsTextField.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Enter comments.", "warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        try
        {

            String message = commentsTextField.getText();

            NeedHelpWorkRequest needHelpWorkRequest = new NeedHelpWorkRequest();
            needHelpWorkRequest.setMessage("Need Help");
            needHelpWorkRequest.setSender(userAccount);
            needHelpWorkRequest.setStatus("Sent");
            needHelpWorkRequest.setNeedHelp(needHelp);
            needHelpWorkRequest.setComments(message);
            needHelpWorkRequest.setRequestDate(new Date());

            UserAccount volunteerAccount = null;
            if (organization!=null){
                for(UserAccount ua: organization.getUserAccountDirectory().getUserAccountList())
                {
                    if(ua.getPerson().getPersonId().equals(volunteer.getPersonId()))
                    {
                        volunteerAccount=ua;
                    }

                }
                volunteerAccount.getWorkQueue().getWorkRequestList().add(needHelpWorkRequest);
                userAccount.getWorkQueue().getWorkRequestList().add(needHelpWorkRequest);
            }
            JOptionPane.showMessageDialog(null, "Request has been created successfully", "success", JOptionPane.PLAIN_MESSAGE);
            commentsTextField.setText("");

        }
        catch(NullPointerException e)
        {
            JOptionPane.showMessageDialog(null, "Unable to send request, Please try again !!", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Unable to send request, Please try again !!", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_submitHelpRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel LastName1;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton cancelHelpRequest;
    private javax.swing.JTextField commentsTextField;
    private javax.swing.JLabel dateOfBirth;
    private javax.swing.JFormattedTextField dobField;
    private javax.swing.JLabel firstName;
    private javax.swing.JLabel firstName1;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel gender1;
    private javax.swing.JTextField genderField;
    private javax.swing.JTextField helpNameTxtField;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JTextField serviceTypeTxtField;
    private javax.swing.JButton submitHelpRequest;
    private javax.swing.JLabel submitRequest;
    private javax.swing.JLabel viewYourProfile;
    private javax.swing.JLabel viewYourProfile1;
    // End of variables declaration//GEN-END:variables
}
