/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.donor;

/**
 *
 * @author keert
 */
public class donationworkarea extends javax.swing.JPanel {

    /**
     * Creates new form donationORKAREA
     */
    public donationworkarea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        manageEnt = new javax.swing.JLabel();
        helpName = new javax.swing.JLabel();
        cardNumberField = new javax.swing.JTextField();
        expiryDate = new javax.swing.JLabel();
        monthField = new javax.swing.JTextField();
        yearField = new javax.swing.JTextField();
        amount = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();
        toAccntNumber = new javax.swing.JLabel();
        toAccntNumberField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();

        manageEnt.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        manageEnt.setText("Make Donation ");

        helpName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        helpName.setText("Enter Card Number (10 Digits)");

        expiryDate.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        expiryDate.setText("Enter Expiry Date(MM/YYYY)");

        amount.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        amount.setText("Enter Amount");

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        name.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        name.setText("Enter Name");

        toAccntNumber.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        toAccntNumber.setText("To Account Number");

        toAccntNumberField.setEditable(false);
        toAccntNumberField.setBackground(new java.awt.Color(204, 255, 204));
        toAccntNumberField.setEnabled(false);

        backJButton.setText("<< back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(449, 449, 449)
                        .add(manageEnt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 201, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(43, 43, 43)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(backJButton)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(toAccntNumber)
                                .add(18, 18, 18)
                                .add(toAccntNumberField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 196, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(0, 359, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(helpName)
                    .add(amount)
                    .add(name)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(submitBtn)
                        .add(expiryDate)))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(nameTxtField)
                            .add(amountField)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(monthField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(yearField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(cardNumberField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 246, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(33, 33, 33)
                        .add(cancelBtn)))
                .add(312, 312, 312))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(manageEnt)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(toAccntNumber)
                    .add(toAccntNumberField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(75, 75, 75)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(name)
                    .add(nameTxtField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(helpName)
                    .add(cardNumberField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(monthField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(expiryDate)
                    .add(yearField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(amount)
                    .add(amountField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 60, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(submitBtn)
                    .add(cancelBtn))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(backJButton)
                .add(52, 52, 52))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1112, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 474, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        if(nameTxtField.getText().trim().isEmpty() ||
            cardNumberField.getText().length()>10 ||
            monthField.getText().length()>2 ||
            yearField.getText().length()>4 || amountField.getText().length()<0)
        {
            JOptionPane.showMessageDialog(null, "Please enter valid input!", "warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        try
        {
            int month = Integer.parseInt(monthField.getText());
            int year = Integer.parseInt(yearField.getText());
            if(month<0 || month > 12)
            {
                JOptionPane.showMessageDialog(null, "Please enter month between 1 and 12!", "warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(year<2015 || year>2050)
            {
                JOptionPane.showMessageDialog(null, "Please enter valid expiry year!", "warning",JOptionPane.WARNING_MESSAGE);
                return;
            }

            DateFormat df = new SimpleDateFormat("EEE, MMM d, YYYY hh:mm aaa");
            Calendar cal = Calendar.getInstance();
            String timestamp = df.format(cal.getTime());

            Donation donation = userAccount.getPerson().addDonation();

            donation.setAmount(amountField.getText());
            donation.setDonationDate(timestamp);
            donation.setAccntName(nameTxtField.getText());
            donation.setAccntNumber(cardNumberField.getText());

            try
            {
                DonationRequest donationRequest = new DonationRequest();
                donationRequest.setDonation(donation);
                donationRequest.setDonatedBy(userAccount.getUserName());
                donationRequest.setSender(userAccount);
                donationRequest.setRequestDate(new Date());
                donationRequest.setMessage("Donated Money");

                userAccount.getWorkQueue().getWorkRequestList().add(donationRequest);

                UserAccount ua = getHeartHelpManagerAccnt();
                if(ua==null)
                {
                    JOptionPane.showMessageDialog(null, "Please verify if heart help manager acccount exists!", "warning",JOptionPane.WARNING_MESSAGE);
                    userAccount.getWorkQueue().getWorkRequestList().remove(donationRequest);
                    return;
                }
                if(ua!=null)
                {
                    donationRequest.setReceiver(ua);
                    donationRequest.setResolveDate(new Date());
                    ua.getWorkQueue().getWorkRequestList().add(donationRequest);
                    donationRequest.setStatus("Completed");
                    JOptionPane.showMessageDialog(null, "Donation has been made successfully, Thank You", "success",JOptionPane.PLAIN_MESSAGE);
                }
                else
                {
                    userAccount.getWorkQueue().getWorkRequestList().remove(donationRequest);
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Please verify if heart help manager acccount exists!", "warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            resetFields();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please enter valid data!", "warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        resetFields();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private javax.swing.JTextField amountField;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField cardNumberField;
    private javax.swing.JLabel expiryDate;
    private javax.swing.JLabel helpName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel manageEnt;
    private javax.swing.JTextField monthField;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel toAccntNumber;
    private javax.swing.JTextField toAccntNumberField;
    private javax.swing.JTextField yearField;
    // End of variables declaration//GEN-END:variables
}
